## supports https://golang.org/s/re2syntax regex syntax
## we expand the string @HOME@ to the current environment
## variable value, however this is the _only_ env var that is
## expanded in this way.
##
## the special tag "NULL" means to remove matching paths from PATH

tag_order = [
  "home_local_bin",
  "home_dot_local_bin",
  "goenv",
  "gopath_bin",
  "rvm",
  "rbenv",
  "pyenv",
  "cargo_bin",
  "home_opt",
  "home_settings_bin",
  "home_bin",
  "nix",
  "ccache",
  "dottools_git",
  "npm_global",
  "twitter_mde",
  "snap",
  "gvm",
  "twitter",
  "hand_compiled",
  "google_cloud",
  "mac_gpg2",
  "nix",
  "brew",
  "npm",
  "postgres",
  "jruby",
  "opt_gnu_bin",
  "debgems",
  "kerberos",
  "linuxbrew",
  "usr_local",
  "usr_bin",
  "slash_bin",
  "pkgsrc",
  "usr_local_conda",
  "all",
  "x11",
]

[patterns]
home_opt           = "\\A@HOME@/local/opt"
home_local_sbin    = "\\A@HOME@/local/sbin"
home_bin           = "\\A@HOME@/bin(?:/|$)"
home_settings_bin  = "\\A@HOME@/.settings/bin(?:/|$)"
home_dot_local_bin = "\\A@HOME@/.local/bin$"
nix                = "(^/nix/|/.nix-profile/)"
linuxbrew          = "\\A/home/linuxbrew/"
ccache             = "/ccache(/|$)"
usr_local_conda    = "\\A/usr/local/anaconda3/bin"
usr_bin            = "\\A/usr/s?bin"
rvm                = "/[.]?rvm(/|$)"
rbenv              = "/[.]?rbenv(/|$)"
gvm                = "/\\.gvm(/|$)"
pyenv              = "/\\.?pyenv(?:-virtualenv)?(/|$)"
goenv              = "/\\.goenv(/|$)"
cargo_bin          = "/\\.cargo/bin(/|$)"
snap               = "\\A/snap/bin"
twpython_27        = "/twpython/CPython-2\\.7"
twpython_26        = "/twpython/CPython-2\\.6"
twpython_rest      = "/twpython/"
twitter_mde        = "\\A/opt/twitter_mde/"
mac_gpg22          = "\\A/usr/local/MacGPG2/"
hand_compiled      = "\\A/opt/jds"
munki              = "/munki($|/)"
brew               = "\\A(?:/usr/local/(bin|sbin|opt/fzf/bin)$)"
slash_bin          = "\\A/s?bin$"
kerberos           = "kerberos/bin"
x11                = "\\A(/usr/X11R6/|/opt/X11/)"
npm                = "/npm/bin"
usr_local          = "\\A/usr/local"
npm_global         = "/\\.?npm-global/bin"
postgres           = "/postgres/\\d\\.\\d/bin"
debgems            = "/var/lib/gems/1\\.\\d/bin"
NULL               = "\\A/Library/PostgreSQL/8\\.\\d/bin"
dottools_git       = "/\\.tools-cache/.*/git\\.Darwin\\.x86\\_64/bin"
dottools           = "/\\.tools-cache/"
twitter            = "(?:twitools|/twitter/|^/opt/local-lite/bin)"
